// Generated by RegForge //
// Try RegForge here - https://github.com/iammituraj/RegForge

// Module name   : uart_regblock
// Description   : Regblock with APB IF
// Date          : 2026-06-09 22:32:32

// Module definition
module uart_regblock (
   //================================================
   // Clocks & Resets
   //================================================
   input  logic         clk,
   input  logic         resetn,  // Async active-low

   //================================================
   // APB Interface
   //================================================
   input  logic   [7:0] i_paddr,
   input  logic         i_psel,
   input  logic         i_penable,
   input  logic         i_pwrite,
   input  logic  [31:0] i_pwdata,
   input  logic   [3:0] i_pstrb,
   output logic  [31:0] o_prdata,
   output logic         o_pready,

   //================================================
   // HW Interface
   //================================================

   // HW Inputs  //

   input  logic   [7:0] i_rxdata_byte,

   input  logic         i_status_tx_busy,
   input  logic         i_status_rx_valid,

   input  logic   [1:0] i_intr_err_setb,
   input  logic   [3:0] i_intr_err_code,
   input  logic         i_intr_err_code_wen,
   input  logic         i_intr_tx_intr_sts_set,
   input  logic         i_intr_rx_intr_sts_set,

   // HW Outputs //

   output logic   [7:0] o_txdata_byte,
   output logic         o_txdata_byte_wtrig,

   output logic         o_rxdata_byte_rtrig,

   output logic         o_control_txen,
   output logic         o_control_rxen,
   output logic         o_control_reset,
   output logic  [15:0] o_control_baud_div,

   output logic         o_intr_tx_intr_en,
   output logic         o_intr_rx_intr_en,
   output logic   [1:0] o_intr_err_clr_w1trig
);

//================================================
// Register Address Map
//================================================
localparam TXDATA_ADDR  = 8'h0;
localparam RXDATA_ADDR  = 8'h4;
localparam CONTROL_ADDR = 8'h8;
localparam STATUS_ADDR  = 8'hC;
localparam INTR_ADDR    = 8'h10;
localparam ID_ADDR      = 8'h14;

//================================================
// APB decoded signals
//================================================
logic   [7:0] paddr;
logic  [31:0] prdata;
logic         req_rd, req_wr, sw_wren, sw_rden;

localparam ADDR_LSB = $clog2(32/8);
assign paddr = {i_paddr[7:ADDR_LSB], {ADDR_LSB{1'b0}}};

//================================================
// APB IF Control FSM
//================================================
// FSM states
typedef enum logic [1:0]
{
   IDLE     = 2'b00,
   W_ACCESS = 2'b01,
   R_ACCESS = 2'b10,
   R_FINISH = 2'b11
}  state_t;
// State register
state_t state_ff;

// Read/write requests
assign req_rd  = i_psel && ~i_pwrite;
assign req_wr  = i_psel &&  i_pwrite;
assign sw_wren = (state_ff == W_ACCESS) && req_wr && i_penable;
assign sw_rden = (state_ff == R_ACCESS) && req_rd && i_penable;

// FSM
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      state_ff <= IDLE;
      o_prdata <= 32'h0;
      o_pready <= 1'b0;
   end
   // Out of reset
   else begin
      // APB control FSM
      case (state_ff)

         // Idle State : waits for psel signal and decodes access type
         IDLE : begin
            if (req_wr) begin
               o_pready <= 1'b1;      // Write access has no wait states
               state_ff <= W_ACCESS;
            end       
            else if (req_rd) begin
               o_pready <= 1'b0;      // Read access has wait states
               state_ff <= R_ACCESS;
            end           
         end

         // Write Access State : writes addressed-register
         W_ACCESS : begin
             o_pready <= 1'b0;
             state_ff <= IDLE;
         end

         // Read Access State : reads addressed-register
         R_ACCESS : begin
            o_prdata <= prdata;
            o_pready <= 1'b1;
            state_ff <= R_FINISH;
         end

         // Read Finish state : All read accesses finish here
         R_FINISH : begin
            o_pready <= 1'b0;
            state_ff <= IDLE;
         end

         // Default state
         default : ;

      endcase
   end
end

//================================================
// Register access decode logic
//================================================
wire txdata_hit = (paddr == TXDATA_ADDR);
wire txdata_wr  = txdata_hit && sw_wren;
wire txdata_rd  = txdata_hit && sw_rden;

wire rxdata_hit = (paddr == RXDATA_ADDR);
wire rxdata_wr  = rxdata_hit && sw_wren;
wire rxdata_rd  = rxdata_hit && sw_rden;

wire control_hit = (paddr == CONTROL_ADDR);
wire control_wr  = control_hit && sw_wren;
wire control_rd  = control_hit && sw_rden;

wire status_hit = (paddr == STATUS_ADDR);
wire status_wr  = status_hit && sw_wren;
wire status_rd  = status_hit && sw_rden;

wire intr_hit = (paddr == INTR_ADDR);
wire intr_wr  = intr_hit && sw_wren;
wire intr_rd  = intr_hit && sw_rden;

wire id_hit = (paddr == ID_ADDR);
wire id_wr  = id_hit && sw_wren;
wire id_rd  = id_hit && sw_rden;


//================================================
// Register fields
//================================================
logic   [7:0] txdata_byte;
logic         txdata_byte_wtrig;

logic   [7:0] rxdata_byte;
logic         rxdata_byte_rtrig;

logic         control_txen;
logic         control_rxen;
logic         control_reset;
logic  [15:0] control_baud_div;

logic         status_tx_busy;
logic         status_rx_valid;

logic         intr_tx_intr_en;
logic         intr_rx_intr_en;
logic   [1:0] intr_err;
logic   [1:0] intr_err_clr_w1trig;
logic   [3:0] intr_err_code;
logic         intr_tx_intr_sts;
logic         intr_rx_intr_sts;

logic  [15:0] ID_ID;


//================================================
// Register fields write logic & SWEVT generation
//================================================
// txdata->byte
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      txdata_byte <= 8'h0;
   end
   else begin
      // SW Write
      if (txdata_wr) begin
         if (i_pstrb[0]) txdata_byte[7:0] <= i_pwdata[7:0];
      end
   end
end

// SWEVT: txdata->byte_wtrig
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      txdata_byte_wtrig <= 1'h0;
   end
   // SW Write event pulse
   else if (txdata_wr) begin
      if (|i_pstrb[0:0]) txdata_byte_wtrig <= 1'h1;
   end
   // Clear the SWEVT pulse
   else begin
      txdata_byte_wtrig <= 1'h0;
   end
end

// rxdata->byte
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      rxdata_byte <= 8'h0;
   end
   else begin
      // SW Clear on Read
      if (rxdata_rd) begin
         rxdata_byte <= '0;
      end
      // HW Write
      else begin
         rxdata_byte <= i_rxdata_byte;
      end
   end
end

// SWEVT: rxdata->byte_rtrig
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      rxdata_byte_rtrig <= 1'h0;
   end
   // SW Read event pulse
   else if (rxdata_rd) begin
      rxdata_byte_rtrig <= 1'h1;
   end
   // Clear the SWEVT pulse
   else begin
      rxdata_byte_rtrig <= 1'h0;
   end
end

// control->txen
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      control_txen <= 1'h1;
   end
   else begin
      // SW Write
      if (control_wr) begin
         if (i_pstrb[0]) control_txen <= i_pwdata[0:0];
      end
   end
end

// control->rxen
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      control_rxen <= 1'h0;
   end
   else begin
      // SW Write
      if (control_wr) begin
         if (i_pstrb[0]) control_rxen <= i_pwdata[1:1];
      end
   end
end

// control->reset
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      control_reset <= 1'h0;
   end
   else begin
      // SW Write
      if (control_wr) begin
         if (i_pstrb[0]) control_reset <= i_pwdata[2:2];
      end
      // Clear the pulse
      else begin
         control_reset <= '0;
      end
   end
end

// control->baud_div
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      control_baud_div <= 16'hffff;
   end
   else begin
      // SW Write
      if (control_wr) begin
         if (i_pstrb[2]) control_baud_div[7:0] <= i_pwdata[23:16];
         if (i_pstrb[3]) control_baud_div[15:8] <= i_pwdata[31:24];
      end
   end
end

// status->tx_busy
assign status_tx_busy = i_status_tx_busy;

// status->rx_valid
assign status_rx_valid = i_status_rx_valid;

// intr->tx_intr_en
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_tx_intr_en <= 1'h0;
   end
   else begin
      // SW Write
      if (intr_wr) begin
         if (i_pstrb[0]) intr_tx_intr_en <= i_pwdata[0:0];
      end
   end
end

// intr->rx_intr_en
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_rx_intr_en <= 1'h0;
   end
   else begin
      // SW Write
      if (intr_wr) begin
         if (i_pstrb[0]) intr_rx_intr_en <= i_pwdata[1:1];
      end
   end
end

// intr->err
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_err <= 2'h0;
   end
   else begin
      // SW Write
      if (i_pstrb[1] && intr_wr) begin
         intr_err[1:0] <= i_pwdata[9:8];
      end
      // HW Write
      else begin
         intr_err[1:0] <= intr_err[1:0] | i_intr_err_setb[1:0];
      end
   end
end

// SWEVT: intr->err_clr_w1trig
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_err_clr_w1trig <= 2'h0;
   end
   // SW Write 1 event pulse
   else if (intr_wr) begin
      if (i_pstrb[1]) intr_err_clr_w1trig[1:0] <= i_pwdata[11:10];
   end
   // Clear the SWEVT pulse
   else begin
      intr_err_clr_w1trig <= '0;
   end
end

// intr->err_code
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_err_code <= 4'h0;
   end
   else begin
      // SW Write
      if (intr_wr) begin
         if (i_pstrb[1]) intr_err_code[3:0] <= i_pwdata[15:12];
      end
      // HW Write
      else begin
         intr_err_code <= i_intr_err_code_wen ? i_intr_err_code : intr_err_code;
      end
   end
end

// intr->tx_intr_sts
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_tx_intr_sts <= 1'h0;
   end
   else begin
      // SW Write
      if (intr_wr) begin
         if (i_pstrb[2]) intr_tx_intr_sts <= intr_tx_intr_sts & ~i_pwdata[16:16];
      end
      // HW Write
      else begin
         intr_tx_intr_sts <= i_intr_tx_intr_sts_set ? '1 : intr_tx_intr_sts;
      end
   end
end

// intr->rx_intr_sts
always_ff @(posedge clk or negedge resetn) begin
   // Reset
   if (!resetn) begin
      intr_rx_intr_sts <= 1'h0;
   end
   else begin
      // SW Write
      if (intr_wr) begin
         if (i_pstrb[2]) intr_rx_intr_sts <= intr_rx_intr_sts & ~i_pwdata[17:17];
      end
      // HW Write
      else begin
         intr_rx_intr_sts <= i_intr_rx_intr_sts_set ? '1 : intr_rx_intr_sts;
      end
   end
end

// ID->ID
assign ID_ID = 16'hbeef;


//================================================
// Register fields read values
//================================================
wire   [7:0] r_txdata_byte = txdata_byte;

wire   [7:0] r_rxdata_byte = rxdata_byte;

wire         r_control_txen     = control_txen;
wire         r_control_rxen     = control_rxen;
wire         r_control_reset    = control_reset;
wire  [12:0] r_control_RSVD     = 13'h0;
wire  [15:0] r_control_baud_div = control_baud_div;

wire         r_status_tx_busy  = status_tx_busy;
wire         r_status_rx_valid = status_rx_valid;

wire         r_intr_tx_intr_en  = intr_tx_intr_en;
wire         r_intr_rx_intr_en  = intr_rx_intr_en;
wire   [1:0] r_intr_err         = intr_err;
wire   [1:0] r_intr_err_clr     = 2'h0;
wire   [3:0] r_intr_err_code    = intr_err_code;
wire         r_intr_tx_intr_sts = intr_tx_intr_sts;
wire         r_intr_rx_intr_sts = intr_rx_intr_sts;

wire  [15:0] r_ID_ID = ID_ID;


//================================================
// Read Data Mux
//================================================
always_comb begin
   if (!sw_rden) begin
      prdata = 32'h0; 
   end
   else begin
      case (paddr)
         TXDATA_ADDR  : prdata = {24'h0, r_txdata_byte};
         RXDATA_ADDR  : prdata = {24'h0, r_rxdata_byte};
         CONTROL_ADDR : prdata = {r_control_baud_div, r_control_RSVD, r_control_reset, r_control_rxen, r_control_txen};
         STATUS_ADDR  : prdata = {30'h0, r_status_rx_valid, r_status_tx_busy};
         INTR_ADDR    : prdata = {14'h0, r_intr_rx_intr_sts, r_intr_tx_intr_sts, r_intr_err_code, r_intr_err_clr, r_intr_err, 6'h0, r_intr_rx_intr_en, r_intr_tx_intr_en};
         ID_ADDR      : prdata = {r_ID_ID, 16'h0};
         default      : prdata = 32'h0;
      endcase
   end
end

//================================================
// HW Outputs
//================================================
assign o_txdata_byte       = txdata_byte;
assign o_txdata_byte_wtrig = txdata_byte_wtrig;

assign o_rxdata_byte_rtrig = rxdata_byte_rtrig;

assign o_control_txen     = control_txen;
assign o_control_rxen     = control_rxen;
assign o_control_reset    = control_reset;
assign o_control_baud_div = control_baud_div;

assign o_intr_tx_intr_en     = intr_tx_intr_en;
assign o_intr_rx_intr_en     = intr_rx_intr_en;
assign o_intr_err_clr_w1trig = intr_err_clr_w1trig;


endmodule